export const SET_THEME = 'SET_THEME';
export const SET_UI_LOGIN_BTN = 'SET_UI_LOGIN_BTN';
export const SET_UI_NOTIFICATION = 'SET_UI_NOTIFICATION';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const SET_NAV_FIXED = 'SET_NAV_FIXED';
export const SET_USER_INFO = 'SET_USER_INFO';

//modal
export const SET_CART_NOTIFICATION_ACT = 'SET_CART_NOTIFICATION_ACT';
export const SET_CONFIRM_CODE_MODAL_ACT = 'SET_CONFIRM_CODE_MODAL_ACT';
export const SET_ADD_VISA_CARD_MODAL_ACT = 'SET_ADD_VISA_CARD_MODAL_ACT';
export const SET_NOTIFATION_MODAL_ACT = 'SET_NOTIFATION_MODAL_ACT';
export const SET_REGISTER_SUCCESS_MODAL_ACT = 'SET_REGISTER_SUCCESS_MODAL_ACT';

//user function
export const USER_FUNCTION = {
  ORDER_MANAGER: 'ORDER_MANAGER',
  USER_INFO: 'USER_INFO',
  NOTIFICATION: 'NOTIFICATION',
  ADDRESS: 'ADDRESS',
  MY_DISCOUNT: 'MY_DISCOUNT',
  MY_FAVORITE: 'MY_FAVORITE',
  HISTORY: 'HISTORY',
};
